# Generated by Django 2.1.2 on 2018-10-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buscas',
            fields=[
                ('id_busca', models.AutoField(primary_key=True, serialize=False)),
                ('forma_busca', models.TextField()),
                ('texto_busca', models.TextField()),
                ('dataIni_busca', models.DateTimeField()),
                ('dataFim_busca', models.DateTimeField()),
                ('qtdTema_proximidades_busca', models.IntegerField(default=0)),
                ('resultadoTema_busca', models.TextField()),
                ('qtdAssuntos_proximidades_busca', models.IntegerField(default=0)),
                ('resultadoAssuntos_proximidades_busca', models.TextField()),
            ],
        ),
    ]
