# Generated by Django 2.1.2 on 2018-10-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscas',
            name='dataFim_busca',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buscas',
            name='resultadoAssuntos_proximidades_busca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buscas',
            name='resultadoTema_busca',
            field=models.TextField(blank=True, null=True),
        ),
    ]
