# Generated by Django 2.1.2 on 2018-10-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0002_auto_20181009_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscas',
            name='processado_busca',
            field=models.BooleanField(default=False),
        ),
    ]
