# Generated by Django 2.1.2 on 2018-10-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0003_buscas_processado_busca'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscas',
            name='caminho_arquivo',
            field=models.TextField(default=''),
        ),
    ]
