# Generated by Django 2.1.2 on 2018-10-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0004_buscas_caminho_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscas',
            name='caminho_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='buscas',
            name='resultado_Grafo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
