# Generated by Django 2.1.2 on 2018-10-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0006_auto_20181024_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='buscas',
            name='tipoBusca',
            field=models.IntegerField(default=0),
        ),
    ]
