# Generated by Django 2.1.2 on 2020-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processamento', '0008_buscas_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id_config', models.IntegerField(primary_key=True, serialize=False)),
                ('idioma', models.TextField(default='')),
                ('linguagem', models.TextField(default='')),
                ('caminho_raiz_programas', models.TextField(default='')),
                ('caminho_padrao_arquivo', models.TextField(default='')),
            ],
        ),
    ]
